### ISSUE TITLE
Routing playbook requires a certain version of jinja2 filter

### ISSUE THREAD

**Issue by snoby** [nicusX/k8s-terraform-ansible-sample#1]
It seems as though a filter used in setting up the routing in the kubernetes-routing.yaml playbook needs to have version 2.8 of the jinja filter installed:
http://jinja.pocoo.org/docs/dev/changelog/

The filter "equalto" was added in version 2.8
I have version 2.7.2
```
[vagrant@yum-00 kube-ansible]$ sudo yum list| grep -i jinja
python-jinja2.noarch                    2.7.2-2.el7                    @base
```

otherwise this happens:

```
msg: Unexpected failure during module execution.
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 431, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 371, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 359, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 331, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 507, in _do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 740, in do_list
    return list(value)
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 839, in do_map
    for item in seq:
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 931, in _select_or_reject
    if modfunc(func(transfunc(item))):
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 925, in <lambda>
    name, item, args, kwargs)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 438, in call_test
    raise TemplateRuntimeError('no test named %r' % name)
TemplateRuntimeError: no test named 'equalto'

fatal: [worker-02]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
Maybe some sort of python version check should be put in?  Not sure how to do that.

**Comment by nicusX** [comment]
Sounds strange it requires Python 2.8 as I checked my version at the time and it was 2.7.12, as mentioned in the readme.

Checking tooling versions doesn't make much sense to me, if requirement are explicit.
To be on the safe side, I will update the readme making 2.8 a requirement.

Thanks for reporting the issue

**Comment by nicusX** [comment]
Updated readme making Jinja2 2.8 requirement explicit [https://github.com/nicusX/k8s-terraform-ansible-sample/commit/1a69bf992bdd36a131564ce7442a2e303423b800]
Definitely, it does not require Python 2.8 as it works for me with 2.7.12.

Thanks
